name: Build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-spancli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ‘1.17.0’
    - name: Run make
      run: make
